const weatherDataIcons = {
  0: { name: "Despejado", icon: "wi wi-day-sunny" },
  1: { name: "Algo nublado", icon: "wi wi-day-sunny-overcast" },
  2: { name: "Parcialmente nublado", icon: "wi wi-day-cloudy" },
  3: { name: "Nublado", icon: "wi wi-cloudy" },
  45: { name: "Niebla", icon: "wi wi-fog" },
  48: { name: "Niebla", icon: "wi wi-fog" },
  51: { name: "Lloviznas leves", icon: "wi wi-showers" },
  53: { name: "Lloviznas moderadas", icon: "wi wi-showers" },
  55: { name: "Lloviznas intensas", icon: "wi wi-showers" },
  56: { name: "Escarcha leve", icon: "wi wi-snow" },
  57: { name: "Escarcha intensa", icon: "wi wi-snow" },
  61: { name: "Precipitaciones leves", icon: "wi wi-rain" },
  63: { name: "Precipitaciones moderadas", icon: "wi wi-rain" },
  65: { name: "Precipitaciones intensas", icon: "wi wi-rain" },
  66: { name: "Lluvia helada leve", icon: "wi wi-rain-mix" },
  67: { name: "Lluvia helada intensa", icon: "wi wi-rain-mix" },
  71: { name: "Nevadas leves", icon: "wi wi-snow" },
  73: { name: "Nevadas moderadas", icon: "wi wi-snow" },
  75: { name: "Nevadas intensas", icon: "wi wi-snow" },
  77: { name: "Nieve", icon: "wi wi-snow" },
  80: { name: "Chaparrones leves", icon: "wi wi-showers" },
  81: { name: "Chaparrones moderadas", icon: "wi wi-showers" },
  82: { name: "Chaparrones intensas", icon: "wi wi-showers" },
  85: { name: "Nevadas leves", icon: "wi wi-snow" },
  86: { name: "Nevadas intensas", icon: "wi wi-snow" },
  95: { name: "Tormenta", icon: "wi wi-thunderstorm" },
  96: { name: "Tormenta con granizo leve", icon: "wi wi-storm-showers" },
  99: { name: "Tormenta y granizo intenso", icon: "wi wi-storm-showers" },
};
